"""Type stubs for the microx_core extension module."""

HOST_ARCH: str

class MicroxError(Exception): ...
class InstructionDecodeError(MicroxError): ...
class InstructionFetchError(MicroxError): ...
class AddressFaultError(MicroxError): ...
class UnsupportedError(MicroxError): ...

class Executor:
    def __init__(self, addr_size: int, arch: str = "auto") -> None: ...
    def execute(self, max_num_executions: int) -> bool: ...
